name: Release

permissions:
  contents: write

on:
  push:
  pull_request:

defaults:
  run:
    shell: bash --noprofile --norc -CeEuo pipefail {0}

jobs:
  create-release:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - uses: taiki-e/create-gh-release-action@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

  upload-assets:
    needs: create-release
    runs-on: macos-14
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: 10
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: build
        run: |
          pnpm i
          pnpm run build

      - uses: actions/upload-artifact@v4
        with:
          name: main.user.js
          path: main.user.js
      - uses: ncipollo/release-action@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          artifacts: "main.user.js"
          allowUpdates: true
